### ISSUE TITLE
Win32 problems with pyopengl 3.1.3b2

### ISSUE THREAD

**Issue by jonwright** [jonwright/pyopengltk#10]
On a clean environment I seem to reproducibly get 3.1.0 using pip. 
I do not understand how 3.1.3b2 showed up. Perhaps it came from conda? 
Anyway, the problem I hit reproduces with either: 
   `conda install pyopengl` 
or with
   `pip install pyopengl --pre`

```
(testpyopengltk) C:\Users\wright>pip install pyopengltk
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyopengltk
  Using cached https://files.pythonhosted.org/packages/3f/7d/2d1b9393d7f1a5f9c3fd676ff5a606efeea772dbb872f3e93716d9fb4ce4/pyopengltk-0.0.3-py2.py3-none-any.whl
Requirement already satisfied: pyopengl in c:\miniconda3\envs\testpyopengltk\lib\site-packages (from pyopengltk) (3.1.3b2)
Installing collected packages: pyopengltk
Successfully installed pyopengltk-0.0.3

(testpyopengltk) C:\Users\wright>python -c "import pyopengltk"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\pyopengltk\__init__.py", line 27, in <module>
    from pyopengltk.win32 import OpenGLFrame
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\pyopengltk\win32.py", line 6, in <module>
    from OpenGL.WGL import PIXELFORMATDESCRIPTOR, ChoosePixelFormat, \
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\OpenGL\WGL\__init__.py", line 1, in <module>
    from OpenGL.raw.WGL.VERSION.WGL_1_0 import *
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\OpenGL\raw\WGL\VERSION\WGL_1_0.py", line 4, in <module>
    from OpenGL.raw.WGL import _types as _cs
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\OpenGL\raw\WGL\_types.py", line 85, in <module>
    _check_size(HANDLE)
NameError: name '_check_size' is not defined
```

_Originally posted by @jonwright in https://github.com/jonwright/pyopengltk/issues/5#issuecomment-541700072_

**Comment by einarf** [comment]
I suspect you have to pin the dependency:
```
conda install pyopengl=3.1.0
```
The recipe on conda-forge says version 3.1.3b2 : https://github.com/conda-forge/pyopengl-feedstock/blob/master/recipe/meta.yaml

I thought there was a separate channel for pre-releases, but that might not be the case.

`pip install --pre` is of course to include pre-releases, so drop that flag and you will get latest stable (3.1.0).

You can also end up getting pre-release packages if you install from source using the old command `python setup.py develop`. `pip install -e .` installs the package in editable mode as a wheel with stable dependencies.

**Comment by jonwright** [comment]
Seems this was fixed elsewhere, closing.
